build:
  environment:
    php: 5.6
  tests:
    override:
      - command: phpunit --coverage-clover=code-coverage
        coverage:
          file: code-coverage
          format: php-clover

checks:
  php: true

filter:
  excluded_paths:
    - tests/*
